
site_name: TrainingData.io
site_description: High Accuracy - Low Effort Image Labeling using Active Learning
site_url: https://docs.trainingdata.io/

# Repository
repo_name: 'AIAssistedImageVideoLabelling'
repo_url: 'https://github.com/trainingdata/AIAssistedImageVideoLabelling/'

# Copyright
copyright: 'Copyright &copy; 2017 - 2019 TrainingData.io'

nav:
      - Overview:
        - FAQ: v1.0/Overview/FAQ.md
        - Complete Feature Set: v1.0/Overview/Complete Feature Set.md
        - Security And Privacy: v1.0/Overview/Data Security.md
        - Quality Management: v1.0/Overview/Quality Control.md
      - Quality Management Workflow:
        - Annotator Performance Management: v1.0/Quality Management Workflow/Annotator Performance Management.md
        - 'Roles: Annotator': v1.0/Quality Management Workflow/Roles-Annotator.md
        - 'Roles: Reviewer': v1.0/Quality Management Workflow/Roles-Reviewer.md
        - 'Roles: Admin': v1.0/Quality Management Workflow/Roles-Admin.md
      - On Premises Infrastructure:
        - Docker and VPN for Secure Training Data: v1.0/Premises Infrastructure/Docker And VPN.md
        - 'Ubuntu: Troubleshooting Docker': v1.0/Premises Infrastructure/Ubuntu Troubleshooting.md
        - 'Windows: Troubleshooting Docker': v1.0/Premises Infrastructure/Windows Troubleshooting.md
        - On-Prem Datasets: v1.0/Premises Infrastructure/Prem Datasets.md
        - Cloud Hosted Datasets: v1.0/Premises Infrastructure/Cloud Hosted Datasets.md
      - Tools:
        - Segmentation with Brush & Eraser: v1.0/Pixel Accurate Tools/Segmentation.md
        - Bounding Box: v1.0/Pixel Accurate Tools/Boundingbox.md
        - Polygon Tool: v1.0/Pixel Accurate Tools/Polygon.md
        - Freehand with Sculpter: v1.0/Pixel Accurate Tools/Freehand.md
        - Key Point Tool: v1.0/Pixel Accurate Tools/PointTool.md
        - Magnify: v1.0/Pixel Accurate Tools/Magnify.md
        - 2D Growth Tool for DICOM: v1.0/Pixel Accurate Tools/Growth Tool.md
      - Labeling Instructions:
        - Labeling Instruction Builder: v1.0/Labelling Interface/Builder.md
        - 'KeyBoard Shortcuts: Productivity': v1.0/Labelling Interface/Keyboard Shortcuts.md
      - AI Assisted Annotation:
        - Segmentation of Liver: v1.0/AI Assisted Annotation/Segmentation Of Liver.md
        - Segmentation of Spleen: v1.0/AI Assisted Annotation/Segmentation Of Spleen.md
      - Export Format:
        - COCO (JSON): v1.0/Export Format/COCO.md
        - Mask (PNG): v1.0/Export Format/Mask.md
        - Tensorflow Records: v1.0/Export Format/TensorFlow Record.md
      - DataSet:
        - Create Cloud Hosted Dataset: v1.0/DataSet/Create Cloud Hosted Dataset.md
        - Create On-Prem Dataset: v1.0/DataSet/Create On-Prem Dataset.md
        - Delete a Dataset: v1.0/DataSet/Delete a Dataset.md
      - Projects:
        - Add New Project: v1.0/Projects/Create a Project.md
        - Start Annotation: v1.0/Projects/Start Annotation.md
      - Collaborators:
        - Add Collaborators to a Specific Project: v1.0/Collaborators/Add Collaborators to Project.md
        - Add a Collaborator: v1.0/Collaborators/Add a Collaborator.md
        - Collaborators: v1.0/Collaborators/Collaborators.md
      - Workspace:
        - Active Viewport Image: v1.0/Workspace/Active Viewport Image.md
        - Folder Navigation: v1.0/Workspace/Folder Navigation.md
        - Label Data: v1.0/Workspace/Label Settings.md
        - ToolBar: v1.0/Workspace/ToolBar.md
      - Terms and Conditions:
        - Privacy Policy: v1.0/Terms and Conditions/Privacy Policy.md
        - Terms of Use: v1.0/Terms and Conditions/Terms of Use.md

      # - Accuracy: v1.0/Accurate Annotations/Freehand Draw.md
      # - Labeling Interface: v1.0/Labelling Interface/Define Labeling Interface.md
      # - Dataset: v1.0/DataSet/Dataset.md
      # - Project: v1.0/Projects/Projects.md
      # - Collaborators: v1.0/Collaborators/Collaborators.md
      # - Workspace: v1.0/Workspace/Folder Navigation -left-.md
      # - On Premises Infrastructure: v1.0/Premises Infrastructure/PremisesInfrastructure.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/logo.jpg'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/trainingdata/AIAssistedImageVideoLabelling/'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/trainingdata/'

extra_css:
- 'assets/extra.css'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#    - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_javascript:
    hubspotscript.js